# Base image.
FROM tomcat:8.5.73

# Author/Maintainer; This will be visible from docker inspect with the other labels.
LABEL author.name="Aniket Pandey"

# Copying war file to tomcat server.
ADD Survey.war /usr/local/tomcat/webapps/